[build]
  command = "CI='' npm run build"
  publish = "frontend/build"
  base = "frontend"
  ignore = "/bin/false"

[build.environment]
  REACT_APP_URL = "https://auction-web-application.herokuapp.com"